import Header from "@/components/Header";
import { fetchData } from "@/utils/fetchData";
import type { Metadata } from "next";
import Script from "next/script";

import "@/styles/globals.scss";
import Footer from "@/components/Footer";
import { globalData } from "@/types/global";
import LdJsonScript from "@/components/LdJsonScript";

export const metadata: Metadata = {
  title: "Moises AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const globalData: globalData = await fetchData('global');

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": globalData.siteName,
    "url": "https://moisesai.com",
    "logo": "https://moisesai.com/images/logo.png",
    "sameAs": Object.values(globalData?.social).map(link => link)
  };

  return (
    <html lang="en">
      <LdJsonScript id="schema" jsonLd={jsonLd} />
      <body>
        <Header links={globalData?.menu} />
        <main>{children}</main>
        <Footer
          {...globalData}
        />
      </body>
    </html>
  );
}
